export const carBrands = [
  'Acura',
  'Alfa Romeo',
  'Audi',
  'BMW',
  'Bentley',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Fiat',
  'Ford',
  'Genesis',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land_Rover',
  'Lexus',
  'Lincoln',
  'Lotus',
  'Maserati',
  'Mazda',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Pontiac',
  'Porsche',
  'Rolls-Royce',
  'Saab',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];

export const carModels = [
  'A3 E-Tron',
  'A5 Ambition Luxe',
  'A7 Quattro Sportback',
  '5-Series 520i',
  '7-Series 740i_Sedan',
  'X5 xLine SUV',
  'Volt LT',
  'Traverse Premier',
  'Suburban Premier',
  'Mustang EcoBoost',
  'Mustang V6 Premium',
  'Accord',
  'Civic NGV',
  'CR-V',
  'GS 450h Hybrid',
  'IS 350 F Sport',
  'LS 460 F-Sport',
  'EV6 GT-line',
  'Forte LXS',
  'Optima Plug-In Hybrid',
  'Sportage Sense',
  'Cherokee Longitude',
  'Wrangler Sport',
  'GranTurismo',
  'Quattroporte GT',
  'CX-9 Touring',
  'MX-5 Miata',
  'AMG GT',
  'CLA Sedan',
  'Clubman Cooper',
  '718 Boxster',
  '911 Carrera_S',
  'Panamera 4 E-Hybrid',
  'Model S',
  'Camry XLE Hybrid',
  'Corolla',
  'Hilux GL',
  'Land Cruiser',
  'Prius',
];